
<field:title itemname="标题" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:title>

<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:tel itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>

<field:email itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:address itemname="地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:address>

<field:content itemname="内容" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:content>

<field:liuyantime itemname="提交时间" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:liuyantime>
