<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/210420/1-161Y05c1-WZ.jpg ",92,237);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/210420/1-161Y05c1-WZ.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="720";
$z[1][4]['height']="540";
$z[2]=Array("img"," /uploads/allimg/210420/1-161Y05c1-4C9.jpg ",238,385);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/210420/1-161Y05c1-4C9.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="720";
$z[2][4]['height']="540";
$z[3]=Array("img"," /uploads/allimg/210420/1-161Y05c1-1517.jpg ",386,535);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/210420/1-161Y05c1-1517.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="720";
$z[3][4]['height']="540";
$z[4]=Array("img"," /uploads/allimg/210420/1-161Y05c1-5540.jpg ",536,685);
$z[4][4]=array();
$z[4][4]['ddimg']="/uploads/allimg/210420/1-161Y05c1-5540.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="720";
$z[4][4]['height']="540";

?>