<div class="col-sm-4 col-md-4 col-mm-6 product_img" data-move-y="50px">
            <div class="projectitem"> <a href="[field:arcurl/]"> <img src="[field:litpic/]" class="img-thumbnail" alt="[field:title/]"> </a>
              <div class="project_info">
                <p class="title">[field:title/]</p>
                <p class="description">[field:info/]...</p>
              </div>
            </div>
          </div>