<?php
$z[0]=Array("channel","\r\n		  <li><a class=\"biglink\" href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n          ",193,413);
$z[0][4]=array();
$z[0][4]['type']="son";
$z[0][4]['currentstyle']="<li><a class='biglink left_active' href='~typelink~'>~typename~</a></li>";
$z[1]=Array("arclist","\r\n		  <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></li>\r\n          ",577,746);
$z[1][4]=array();
$z[1][4]['typeid']="9";
$z[1][4]['row']="4";
$z[1][4]['titlelen']="90";
$z[1][4]['orderby']="pubdate";
$z[2]=Array("global","",923,945);
$z[2][4]=array();
$z[2][4]['name']="cfg_lxr";
$z[3]=Array("global","",973,995);
$z[3][4]=array();
$z[3][4]['name']="cfg_mob";
$z[4]=Array("global","",1023,1045);
$z[4][4]=array();
$z[4][4]['name']="cfg_tel";
$z[5]=Array("global","",1073,1097);
$z[5][4]=array();
$z[5][4]['name']="cfg_email";
$z[6]=Array("global","",1126,1148);
$z[6][4]=array();
$z[6][4]['name']="cfg_add";

?>